version: "3.1"
services:
  amovieplex_api:
    build: .
    command: realize start --run
    volumes:
      - ".:/opt/app"
    ports:
      - "8080:8080"
    depends_on:
      - backend-mongodb

  backend-mongodb:
    image: mongo
    restart: on-failure
    volumes:
      - "database_vol:/data/db"
    ports:
      - "27017:27017"
volumes:
  database_vol: null
